#!/bin/sh
# Change UID to the one from user
# NOTE: You cannot change the uid of the running process, so this must happen as root. Use -e USERSPACE=1 instead of --user=www-data at docker-compose

set -e
USERNAME="www-data"
GROUPNAME=${USERNAME}

# Change UID of the user, when env var UID is provided
if [ ! -z ${UID} ]; then
    OLDUID=`id -u ${USERNAME}`
    if [ ${OLDUID} != ${UID} ]; then
        usermod -u ${UID} ${USERNAME}
        # Also change permissions on all existing files
        find / -xdev -user ${OLDUID} -exec chown ${UID} {} +
    fi
fi

# Change GID of the user, when env var GID is provided
if [ ! -z ${GID} ]; then
    OLDGID=`id -g ${GROUPNAME}`
    if [ ${OLDGID} != ${GID} ]; then
        groupmod -g ${GID} ${GROUPNAME}
        find / -xdev -group ${OLDGID} -exec chgrp ${GID} {} +
    fi
fi

# Call parent entrypoint (as other user) when needed
if [ ! -z ${USERSPACE} ]; then
	# Downgrade to ${USERNAME}
	su-exec ${USERNAME} docker-php-entrypoint "$@"
else
	# Run as same user (root)
	exec docker-php-entrypoint "$@"
fi
